name: Update PIN Codes and Links

on:
  schedule:
    # Run every 24 hours at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-pins:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run PIN updater
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PASTEBIN_API_KEY: ${{ secrets.PASTEBIN_API_KEY }}
        SHORTENER_API_KEY: ${{ secrets.SHORTENER_API_KEY }}
        TARGET_REPO: ${{ github.repository }}
        TARGET_FILE: 'index.html'
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
      run: python update_pins_final.py
