name: Update PIN Codes and Links

on:
  schedule:
    # Run every 24 hours at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update-pins:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Update PIN codes and links
      env:
        PASTEBIN_API_KEY: ${{ secrets.PASTEBIN_API_KEY }}
        PASTEBIN_USER_KEY: ${{ secrets.PASTEBIN_USER_KEY }}
        SHORTENER_API_KEY: ${{ secrets.SHORTENER_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
        TARGET_REPO: ${{ vars.TARGET_REPO || 'sandy2k25/wbn1' }}
        TARGET_FILE: ${{ vars.TARGET_FILE || 'index.html' }}
      run: |
        python update_pins.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "🔄 Auto-update PIN codes and links - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
        
